### ISSUE TITLE
Failed to run Demo.CrossPlatform.Web

### ISSUE THREAD

**Issue by montex12** [mysteryx93/HanumanInstitute.MvvmDialogs#14]
Hello

I am trying to run Demo.CrossPlatform.Web but seems Chrome cannot reach the page.

First of all the project Demo.CrossPlatform didn't compile because of 'XamlNameReferenceGenerator' which must be removed but after compiling it with success the project above seems to run from debugger but the web browser cannot reach the page.

I am using Visual Studio 2022 + Chrome.

**Comment by mysteryx93** [comment]
I was having a hard time getting the Web project to run on my machine so that one hasn't been tested.

That's probably a local configuration issue. If the project doesn't run at all, then it's not a MvvmDialogs issue.

You can try creating a blank Avalonia template project and see if you can run the Web project there. If you find a problem with the Web app here, let me know and I'll change it.

**Comment by montex12** [comment]
I am using Avalonia 11.0.0-rc1.1 and creating a new template with WebAssembly target seems to work.
I think Demo.CrossPlatform.Web hangs somewhere because probably couldn't initialize the resources and publish the server.

Here's my reference (that works):
https://github.com/AvaloniaUI/avalonia-dotnet-templates/tree/master/templates/csharp/xplat/AvaloniaTest.Browser

**Comment by mysteryx93** [comment]
ok if a blank project works, then I might have to recreate the project from template. Will do that later.

**Comment by mysteryx93** [comment]
Fixed the code so the Web project runs; but the Web demo needs some work.
