### ISSUE TITLE
Allow FileFilter class to filter on specific files vs just extensions

### ISSUE THREAD

**Issue by RyanPoto** [mysteryx93/HanumanInstitute.MvvmDialogs#37]
Currently when using ShowOpenFileDialogAsync and adding a file filter it will always add a " *. " to the front of each filter added in settings. This works for extensions but I would like to filter for a specific set of files so it will only show those, which requires no " *. " to be added at the front. Is there a way around this currently? I'm moving my project from WPF and this was possible using OpenFileDialog since you were manually creating the filter.

**Comment by mysteryx93** [comment]
As of right now... the only way might be to create a custom DialogFactory with a custom implementation.

See the OpenCustomFolderDialog sample
https://github.com/mysteryx93/HanumanInstitute.MvvmDialogs/tree/master/samples/Avalonia/Demo.CustomOpenFolderDialog

Since this is a corner-case and it's possible to create custom implementations, would it be good to edit the code to account for it or better leave the code as-is?

**Comment by RyanPoto** [comment]
Thanks, I will look through the OpenCustomFolderDialog sample. It is up to you whether the code should change but I believe the amount changed would be relatively small. I think just an overload for the FileFilter class which skips the " *. " append in ExtensionsToString would be the only required changes unless I am missing something. If the OpenCustomFolderDialog is very easy to implement then there may be no point.

**Comment by mysteryx93** [comment]
Changing the way it is handled (with or without extension) could possibly be a breaking change though.

And it's pretty easy to implement your customized version.

**Comment by RyanPoto** [comment]
Alright, if it's easy then leave it as is. Thanks for the support on where to look!
